# Site wide configuration

title: #Shruti Palaskar
locale: en_US
url: https://shrutijpalaskar.github.io
# Jekyll configuration
theme: minimal-mistakes-jekyll

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Shruti Palaskar
  avatar: 70763270_10157769016670962_5868038955521277952_o.jpg #try image instead of avatar, try cmlh pic
  position: Graduate Student
  school: Carnegie Mellon University
  place: Pittsburgh, PA.
  bio: "Graduate student<br/>Language Technologies Institute, School of Computer Science&#13;&#10;Carnegie Mellon University&#13;&#10;Pittsburgh, PA"
  email: spalaska@cs.cmu.edu
  disqus-shortname:
  twitter: sjpal94
  facebook:  #username
  google:
    scholar: https://scholar.google.com/citations?user=7bun32IAAAAJ&hl=en&oi=ao
    plus:  #username
    analytics: UA-57438847-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: shrutijpalaskar
  stackoverflow: #username 
  linkedin: shrutipalaskar #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
